# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Independently Variable
tagline:             'A blog of data science'
description:         'Description of my blog'
url:                 http://zeromh.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tim Martin
  url:               https://zeromh.github.io
  email:             zeromh@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
